import type { City } from "../types/city"

export const cities: City[] = [
  { id: "abidjan", label: "Abidjan", tz: "Africa/Abidjan", utcOffset: "+00:00" },
  { id: "abu-dhabi", label: "Abu Dhabi", tz: "Asia/Dubai", utcOffset: "+04:00" },
  { id: "accra", label: "Accra", tz: "Africa/Accra", utcOffset: "+00:00" },
  { id: "addis-ababa", label: "Addis Ababa", tz: "Africa/Addis_Ababa", utcOffset: "+03:00" },
  { id: "adelaide", label: "Adelaide", tz: "Australia/Adelaide", utcOffset: "+10:30" },
  { id: "alexandria", label: "Alexandria", tz: "Africa/Cairo", utcOffset: "+02:00" },
  { id: "algiers", label: "Algiers", tz: "Africa/Algiers", utcOffset: "+01:00" },
  { id: "almaty", label: "Almaty", tz: "Asia/Almaty", utcOffset: "+06:00" },
  { id: "amman", label: "Amman", tz: "Asia/Amman", utcOffset: "+03:00" },
  { id: "amsterdam", label: "Amsterdam", tz: "Europe/Amsterdam", utcOffset: "+01:00" },
  { id: "anchorage", label: "Anchorage", tz: "America/Anchorage", utcOffset: "-09:00" },
  { id: "athens", label: "Athens", tz: "Europe/Athens", utcOffset: "+02:00" },
  { id: "atlanta", label: "Atlanta", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "auckland", label: "Auckland", tz: "Pacific/Auckland", utcOffset: "+13:00" },
  { id: "baghdad", label: "Baghdad", tz: "Asia/Baghdad", utcOffset: "+03:00" },
  { id: "baku", label: "Baku", tz: "Asia/Baku", utcOffset: "+04:00" },
  { id: "bangkok", label: "Bangkok", tz: "Asia/Bangkok", utcOffset: "+07:00" },
  { id: "barcelona", label: "Barcelona", tz: "Europe/Madrid", utcOffset: "+01:00" },
  { id: "beijing", label: "Beijing", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "beirut", label: "Beirut", tz: "Asia/Beirut", utcOffset: "+02:00" },
  { id: "belgrade", label: "Belgrade", tz: "Europe/Belgrade", utcOffset: "+01:00" },
  { id: "bengaluru", label: "Bengaluru", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "berlin", label: "Berlin", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "bogota", label: "Bogota", tz: "America/Bogota", utcOffset: "-05:00" },
  { id: "boston", label: "Boston", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "brasilia", label: "Brasilia", tz: "America/Sao_Paulo", utcOffset: "-03:00" },
  { id: "brisbane", label: "Brisbane", tz: "Australia/Brisbane", utcOffset: "+10:00" },
  { id: "brussels", label: "Brussels", tz: "Europe/Brussels", utcOffset: "+01:00" },
  { id: "bucharest", label: "Bucharest", tz: "Europe/Bucharest", utcOffset: "+02:00" },
  { id: "budapest", label: "Budapest", tz: "Europe/Budapest", utcOffset: "+01:00" },
  { id: "buenos-aires", label: "Buenos Aires", tz: "America/Argentina/Buenos_Aires", utcOffset: "-03:00" },
  { id: "busan", label: "Busan", tz: "Asia/Seoul", utcOffset: "+09:00" },
  { id: "cairo", label: "Cairo", tz: "Africa/Cairo", utcOffset: "+02:00" },
  { id: "calgary", label: "Calgary", tz: "America/Edmonton", utcOffset: "-07:00" },
  { id: "canberra", label: "Canberra", tz: "Australia/Sydney", utcOffset: "+11:00" },
  { id: "cape-town", label: "Cape Town", tz: "Africa/Johannesburg", utcOffset: "+02:00" },
  { id: "caracas", label: "Caracas", tz: "America/Caracas", utcOffset: "-04:00" },
  { id: "casablanca", label: "Casablanca", tz: "Africa/Casablanca", utcOffset: "+01:00" },
  { id: "chennai", label: "Chennai", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "chicago", label: "Chicago", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "chittagong", label: "Chittagong", tz: "Asia/Dhaka", utcOffset: "+06:00" },
  { id: "christchurch", label: "Christchurch", tz: "Pacific/Auckland", utcOffset: "+13:00" },
  { id: "colombo", label: "Colombo", tz: "Asia/Colombo", utcOffset: "+05:30" },
  { id: "copenhagen", label: "Copenhagen", tz: "Europe/Copenhagen", utcOffset: "+01:00" },
  { id: "dakar", label: "Dakar", tz: "Africa/Dakar", utcOffset: "+00:00" },
  { id: "dallas", label: "Dallas", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "dar-es-salaam", label: "Dar es Salaam", tz: "Africa/Dar_es_Salaam", utcOffset: "+03:00" },
  { id: "delhi", label: "Delhi", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "denver", label: "Denver", tz: "America/Denver", utcOffset: "-07:00" },
  { id: "dhaka", label: "Dhaka", tz: "Asia/Dhaka", utcOffset: "+06:00" },
  { id: "doha", label: "Doha", tz: "Asia/Qatar", utcOffset: "+03:00" },
  { id: "dubai", label: "Dubai", tz: "Asia/Dubai", utcOffset: "+04:00" },
  { id: "dublin", label: "Dublin", tz: "Europe/Dublin", utcOffset: "+00:00" },
  { id: "durban", label: "Durban", tz: "Africa/Johannesburg", utcOffset: "+02:00" },
  { id: "edinburgh", label: "Edinburgh", tz: "Europe/London", utcOffset: "+00:00" },
  { id: "edmonton", label: "Edmonton", tz: "America/Edmonton", utcOffset: "-07:00" },
  { id: "frankfurt", label: "Frankfurt", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "fukuoka", label: "Fukuoka", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "geneva", label: "Geneva", tz: "Europe/Zurich", utcOffset: "+01:00" },
  { id: "guangzhou", label: "Guangzhou", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "guatemala-city", label: "Guatemala City", tz: "America/Guatemala", utcOffset: "-06:00" },
  { id: "guayaquil", label: "Guayaquil", tz: "America/Guayaquil", utcOffset: "-05:00" },
  { id: "hamburg", label: "Hamburg", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "hanoi", label: "Hanoi", tz: "Asia/Bangkok", utcOffset: "+07:00" },
  { id: "harare", label: "Harare", tz: "Africa/Harare", utcOffset: "+02:00" },
  { id: "havana", label: "Havana", tz: "America/Havana", utcOffset: "-05:00" },
  { id: "helsinki", label: "Helsinki", tz: "Europe/Helsinki", utcOffset: "+02:00" },
  { id: "ho-chi-minh-city", label: "Ho Chi Minh City", tz: "Asia/Ho_Chi_Minh", utcOffset: "+07:00" },
  { id: "hong-kong", label: "Hong Kong", tz: "Asia/Hong_Kong", utcOffset: "+08:00" },
  { id: "honolulu", label: "Honolulu", tz: "Pacific/Honolulu", utcOffset: "-10:00" },
  { id: "houston", label: "Houston", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "hyderabad", label: "Hyderabad", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "islamabad", label: "Islamabad", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "istanbul", label: "Istanbul", tz: "Europe/Istanbul", utcOffset: "+03:00" },
  { id: "jakarta", label: "Jakarta", tz: "Asia/Jakarta", utcOffset: "+07:00" },
  { id: "jeddah", label: "Jeddah", tz: "Asia/Riyadh", utcOffset: "+03:00" },
  { id: "jerusalem", label: "Jerusalem", tz: "Asia/Jerusalem", utcOffset: "+02:00" },
  { id: "johannesburg", label: "Johannesburg", tz: "Africa/Johannesburg", utcOffset: "+02:00" },
  { id: "kabul", label: "Kabul", tz: "Asia/Kabul", utcOffset: "+04:30" },
  { id: "kampala", label: "Kampala", tz: "Africa/Kampala", utcOffset: "+03:00" },
  { id: "karachi", label: "Karachi", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "kathmandu", label: "Kathmandu", tz: "Asia/Kathmandu", utcOffset: "+05:45" },
  { id: "khartoum", label: "Khartoum", tz: "Africa/Khartoum", utcOffset: "+02:00" },
  { id: "kigali", label: "Kigali", tz: "Africa/Kigali", utcOffset: "+02:00" },
  { id: "kingston", label: "Kingston", tz: "America/Jamaica", utcOffset: "-05:00" },
  { id: "kuala-lumpur", label: "Kuala Lumpur", tz: "Asia/Kuala_Lumpur", utcOffset: "+08:00" },
  { id: "kuwait-city", label: "Kuwait City", tz: "Asia/Kuwait", utcOffset: "+03:00" },
  { id: "kyiv", label: "Kyiv", tz: "Europe/Kyiv", utcOffset: "+02:00" },
  { id: "lagos", label: "Lagos", tz: "Africa/Lagos", utcOffset: "+01:00" },
  { id: "lahore", label: "Lahore", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "la-paz", label: "La Paz", tz: "America/La_Paz", utcOffset: "-04:00" },
  { id: "las-vegas", label: "Las Vegas", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "lima", label: "Lima", tz: "America/Lima", utcOffset: "-05:00" },
  { id: "lisbon", label: "Lisbon", tz: "Europe/Lisbon", utcOffset: "+00:00" },
  { id: "london", label: "London", tz: "Europe/London", utcOffset: "+00:00" },
  { id: "los-angeles", label: "Los Angeles", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "luanda", label: "Luanda", tz: "Africa/Luanda", utcOffset: "+01:00" },
  { id: "luxembourg", label: "Luxembourg", tz: "Europe/Luxembourg", utcOffset: "+01:00" },
  { id: "madrid", label: "Madrid", tz: "Europe/Madrid", utcOffset: "+01:00" },
  { id: "manama", label: "Manama", tz: "Asia/Bahrain", utcOffset: "+03:00" },
  { id: "manila", label: "Manila", tz: "Asia/Manila", utcOffset: "+08:00" },
  { id: "maputo", label: "Maputo", tz: "Africa/Maputo", utcOffset: "+02:00" },
  { id: "medellin", label: "Medellin", tz: "America/Bogota", utcOffset: "-05:00" },
  { id: "melbourne", label: "Melbourne", tz: "Australia/Melbourne", utcOffset: "+11:00" },
  { id: "mexico-city", label: "Mexico City", tz: "America/Mexico_City", utcOffset: "-06:00" },
  { id: "miami", label: "Miami", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "milan", label: "Milan", tz: "Europe/Rome", utcOffset: "+01:00" },
  { id: "minneapolis", label: "Minneapolis", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "montevideo", label: "Montevideo", tz: "America/Montevideo", utcOffset: "-03:00" },
  { id: "montreal", label: "Montreal", tz: "America/Toronto", utcOffset: "-05:00" },
  { id: "moscow", label: "Moscow", tz: "Europe/Moscow", utcOffset: "+03:00" },
  { id: "mumbai", label: "Mumbai", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "munich", label: "Munich", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "muscat", label: "Muscat", tz: "Asia/Muscat", utcOffset: "+04:00" },
  { id: "nairobi", label: "Nairobi", tz: "Africa/Nairobi", utcOffset: "+03:00" },
  { id: "naples", label: "Naples", tz: "Europe/Rome", utcOffset: "+01:00" },
  { id: "new-york", label: "New York", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "osaka", label: "Osaka", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "oslo", label: "Oslo", tz: "Europe/Oslo", utcOffset: "+01:00" },
  { id: "ottawa", label: "Ottawa", tz: "America/Toronto", utcOffset: "-05:00" },
  { id: "panama-city", label: "Panama City", tz: "America/Panama", utcOffset: "-05:00" },
  { id: "paris", label: "Paris", tz: "Europe/Paris", utcOffset: "+01:00" },
  { id: "perth", label: "Perth", tz: "Australia/Perth", utcOffset: "+08:00" },
  { id: "philadelphia", label: "Philadelphia", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "phnom-penh", label: "Phnom Penh", tz: "Asia/Phnom_Penh", utcOffset: "+07:00" },
  { id: "phoenix", label: "Phoenix", tz: "America/Phoenix", utcOffset: "-07:00" },
  { id: "port-moresby", label: "Port Moresby", tz: "Pacific/Port_Moresby", utcOffset: "+10:00" },
  { id: "prague", label: "Prague", tz: "Europe/Prague", utcOffset: "+01:00" },
  { id: "quito", label: "Quito", tz: "America/Guayaquil", utcOffset: "-05:00" },
  { id: "rabat", label: "Rabat", tz: "Africa/Casablanca", utcOffset: "+01:00" },
  { id: "rio-de-janeiro", label: "Rio de Janeiro", tz: "America/Sao_Paulo", utcOffset: "-03:00" },
  { id: "riyadh", label: "Riyadh", tz: "Asia/Riyadh", utcOffset: "+03:00" },
  { id: "rome", label: "Rome", tz: "Europe/Rome", utcOffset: "+01:00" },
  { id: "san-diego", label: "San Diego", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "san-francisco", label: "San Francisco", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "san-jose", label: "San Jose", tz: "America/Costa_Rica", utcOffset: "-06:00" },
  { id: "san-juan", label: "San Juan", tz: "America/Puerto_Rico", utcOffset: "-04:00" },
  { id: "santiago", label: "Santiago", tz: "America/Santiago", utcOffset: "-03:00" },
  { id: "sao-paulo", label: "Sao Paulo", tz: "America/Sao_Paulo", utcOffset: "-03:00" },
  { id: "seattle", label: "Seattle", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "seoul", label: "Seoul", tz: "Asia/Seoul", utcOffset: "+09:00" },
  { id: "shanghai", label: "Shanghai", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "shenzhen", label: "Shenzhen", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "singapore", label: "Singapore", tz: "Asia/Singapore", utcOffset: "+08:00" },
  { id: "sofia", label: "Sofia", tz: "Europe/Sofia", utcOffset: "+02:00" },
  { id: "stockholm", label: "Stockholm", tz: "Europe/Stockholm", utcOffset: "+01:00" },
  { id: "st-petersburg", label: "St Petersburg", tz: "Europe/Moscow", utcOffset: "+03:00" },
  { id: "suva", label: "Suva", tz: "Pacific/Fiji", utcOffset: "+12:00" },
  { id: "sydney", label: "Sydney", tz: "Australia/Sydney", utcOffset: "+11:00" },
  { id: "tallinn", label: "Tallinn", tz: "Europe/Tallinn", utcOffset: "+02:00" },
  { id: "tashkent", label: "Tashkent", tz: "Asia/Tashkent", utcOffset: "+05:00" },
  { id: "tehran", label: "Tehran", tz: "Asia/Tehran", utcOffset: "+03:30" },
  { id: "tel-aviv", label: "Tel Aviv", tz: "Asia/Jerusalem", utcOffset: "+02:00" },
  { id: "tokyo", label: "Tokyo", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "toronto", label: "Toronto", tz: "America/Toronto", utcOffset: "-05:00" },
  { id: "tripoli", label: "Tripoli", tz: "Africa/Tripoli", utcOffset: "+02:00" },
  { id: "tunis", label: "Tunis", tz: "Africa/Tunis", utcOffset: "+01:00" },
  { id: "ulaanbaatar", label: "Ulaanbaatar", tz: "Asia/Ulaanbaatar", utcOffset: "+08:00" },
  { id: "vancouver", label: "Vancouver", tz: "America/Vancouver", utcOffset: "-08:00" },
  { id: "vienna", label: "Vienna", tz: "Europe/Vienna", utcOffset: "+01:00" },
  { id: "vientiane", label: "Vientiane", tz: "Asia/Vientiane", utcOffset: "+07:00" },
  { id: "vilnius", label: "Vilnius", tz: "Europe/Vilnius", utcOffset: "+02:00" },
  { id: "warsaw", label: "Warsaw", tz: "Europe/Warsaw", utcOffset: "+01:00" },
  { id: "washington-dc", label: "Washington DC", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "wellington", label: "Wellington", tz: "Pacific/Auckland", utcOffset: "+13:00" },
  { id: "windhoek", label: "Windhoek", tz: "Africa/Windhoek", utcOffset: "+02:00" },
  { id: "yangon", label: "Yangon", tz: "Asia/Yangon", utcOffset: "+06:30" },
  { id: "yaounde", label: "Yaounde", tz: "Africa/Douala", utcOffset: "+01:00" },
  { id: "yerevan", label: "Yerevan", tz: "Asia/Yerevan", utcOffset: "+04:00" },
  { id: "zagreb", label: "Zagreb", tz: "Europe/Zagreb", utcOffset: "+01:00" },
  { id: "zurich", label: "Zurich", tz: "Europe/Zurich", utcOffset: "+01:00" },
]
