import type { City } from "../types/city"

export const allCities: City[] = [
  { id: "abidjan", label: "Abidjan", flag: "🇨🇮", tz: "Africa/Abidjan", utcOffset: "+00:00" },
  { id: "abu-dhabi", label: "Abu Dhabi", flag: "🇦🇪", tz: "Asia/Dubai", utcOffset: "+04:00" },
  { id: "accra", label: "Accra", flag: "🇬🇭", tz: "Africa/Accra", utcOffset: "+00:00" },
  {
    id: "addis-ababa",
    label: "Addis Ababa",
    flag: "🇪🇹",
    tz: "Africa/Addis_Ababa",
    utcOffset: "+03:00",
  },
  { id: "adelaide", label: "Adelaide", flag: "🇦🇺", tz: "Australia/Adelaide", utcOffset: "+10:30" },
  { id: "alexandria", label: "Alexandria", flag: "🇪🇬", tz: "Africa/Cairo", utcOffset: "+02:00" },
  { id: "algiers", label: "Algiers", flag: "🇩🇿", tz: "Africa/Algiers", utcOffset: "+01:00" },
  { id: "almaty", label: "Almaty", flag: "🇰🇿", tz: "Asia/Almaty", utcOffset: "+06:00" },
  { id: "amman", label: "Amman", flag: "🇯🇴", tz: "Asia/Amman", utcOffset: "+03:00" },
  { id: "amsterdam", label: "Amsterdam", flag: "🇳🇱", tz: "Europe/Amsterdam", utcOffset: "+01:00" },
  { id: "anchorage", label: "Anchorage", flag: "🇺🇸", tz: "America/Anchorage", utcOffset: "-09:00" },
  { id: "athens", label: "Athens", flag: "🇬🇷", tz: "Europe/Athens", utcOffset: "+02:00" },
  { id: "atlanta", label: "Atlanta", flag: "🇺🇸", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "auckland", label: "Auckland", flag: "🇳🇿", tz: "Pacific/Auckland", utcOffset: "+13:00" },
  { id: "baghdad", label: "Baghdad", flag: "🇮🇶", tz: "Asia/Baghdad", utcOffset: "+03:00" },
  { id: "baku", label: "Baku", flag: "🇦🇿", tz: "Asia/Baku", utcOffset: "+04:00" },
  { id: "bangkok", label: "Bangkok", flag: "🇹🇭", tz: "Asia/Bangkok", utcOffset: "+07:00" },
  { id: "barcelona", label: "Barcelona", flag: "🇪🇸", tz: "Europe/Madrid", utcOffset: "+01:00" },
  { id: "beijing", label: "Beijing", flag: "🇨🇳", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "beirut", label: "Beirut", flag: "🇱🇧", tz: "Asia/Beirut", utcOffset: "+02:00" },
  { id: "belgrade", label: "Belgrade", flag: "🇷🇸", tz: "Europe/Belgrade", utcOffset: "+01:00" },
  { id: "bengaluru", label: "Bengaluru", flag: "🇮🇳", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "berlin", label: "Berlin", flag: "🇩🇪", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "bogota", label: "Bogota", flag: "🇨🇴", tz: "America/Bogota", utcOffset: "-05:00" },
  { id: "boston", label: "Boston", flag: "🇺🇸", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "brasilia", label: "Brasilia", flag: "🇧🇷", tz: "America/Sao_Paulo", utcOffset: "-03:00" },
  { id: "brisbane", label: "Brisbane", flag: "🇦🇺", tz: "Australia/Brisbane", utcOffset: "+10:00" },
  { id: "brussels", label: "Brussels", flag: "🇧🇪", tz: "Europe/Brussels", utcOffset: "+01:00" },
  { id: "bucharest", label: "Bucharest", flag: "🇷🇴", tz: "Europe/Bucharest", utcOffset: "+02:00" },
  { id: "budapest", label: "Budapest", flag: "🇭🇺", tz: "Europe/Budapest", utcOffset: "+01:00" },
  {
    id: "buenos-aires",
    label: "Buenos Aires",
    flag: "🇦🇷",
    tz: "America/Argentina/Buenos_Aires",
    utcOffset: "-03:00",
  },
  { id: "busan", label: "Busan", flag: "🇰🇷", tz: "Asia/Seoul", utcOffset: "+09:00" },
  { id: "cairo", label: "Cairo", flag: "🇪🇬", tz: "Africa/Cairo", utcOffset: "+02:00" },
  { id: "calgary", label: "Calgary", flag: "🇨🇦", tz: "America/Edmonton", utcOffset: "-07:00" },
  { id: "canberra", label: "Canberra", flag: "🇦🇺", tz: "Australia/Sydney", utcOffset: "+11:00" },
  {
    id: "cape-town",
    label: "Cape Town",
    flag: "🇿🇦",
    tz: "Africa/Johannesburg",
    utcOffset: "+02:00",
  },
  { id: "caracas", label: "Caracas", flag: "🇻🇪", tz: "America/Caracas", utcOffset: "-04:00" },
  {
    id: "casablanca",
    label: "Casablanca",
    flag: "🇲🇦",
    tz: "Africa/Casablanca",
    utcOffset: "+01:00",
  },
  { id: "chennai", label: "Chennai", flag: "🇮🇳", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "chicago", label: "Chicago", flag: "🇺🇸", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "chittagong", label: "Chittagong", flag: "🇧🇩", tz: "Asia/Dhaka", utcOffset: "+06:00" },
  {
    id: "christchurch",
    label: "Christchurch",
    flag: "🇳🇿",
    tz: "Pacific/Auckland",
    utcOffset: "+13:00",
  },
  { id: "colombo", label: "Colombo", flag: "🇱🇰", tz: "Asia/Colombo", utcOffset: "+05:30" },
  {
    id: "copenhagen",
    label: "Copenhagen",
    flag: "🇩🇰",
    tz: "Europe/Copenhagen",
    utcOffset: "+01:00",
  },
  { id: "dakar", label: "Dakar", flag: "🇸🇳", tz: "Africa/Dakar", utcOffset: "+00:00" },
  { id: "dallas", label: "Dallas", flag: "🇺🇸", tz: "America/Chicago", utcOffset: "-06:00" },
  {
    id: "dar-es-salaam",
    label: "Dar es Salaam",
    flag: "🇹🇿",
    tz: "Africa/Dar_es_Salaam",
    utcOffset: "+03:00",
  },
  { id: "delhi", label: "Delhi", flag: "🇮🇳", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "denver", label: "Denver", flag: "🇺🇸", tz: "America/Denver", utcOffset: "-07:00" },
  { id: "dhaka", label: "Dhaka", flag: "🇧🇩", tz: "Asia/Dhaka", utcOffset: "+06:00" },
  { id: "doha", label: "Doha", flag: "🇶🇦", tz: "Asia/Qatar", utcOffset: "+03:00" },
  { id: "dubai", label: "Dubai", flag: "🇦🇪", tz: "Asia/Dubai", utcOffset: "+04:00" },
  { id: "dublin", label: "Dublin", flag: "🇮🇪", tz: "Europe/Dublin", utcOffset: "+00:00" },
  { id: "durban", label: "Durban", flag: "🇿🇦", tz: "Africa/Johannesburg", utcOffset: "+02:00" },
  { id: "edinburgh", label: "Edinburgh", flag: "🇬🇧", tz: "Europe/London", utcOffset: "+00:00" },
  { id: "edmonton", label: "Edmonton", flag: "🇨🇦", tz: "America/Edmonton", utcOffset: "-07:00" },
  { id: "frankfurt", label: "Frankfurt", flag: "🇩🇪", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "fukuoka", label: "Fukuoka", flag: "🇯🇵", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "geneva", label: "Geneva", flag: "🇨🇭", tz: "Europe/Zurich", utcOffset: "+01:00" },
  { id: "guangzhou", label: "Guangzhou", flag: "🇨🇳", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  {
    id: "guatemala-city",
    label: "Guatemala City",
    flag: "🇬🇹",
    tz: "America/Guatemala",
    utcOffset: "-06:00",
  },
  { id: "guayaquil", label: "Guayaquil", flag: "🇪🇨", tz: "America/Guayaquil", utcOffset: "-05:00" },
  { id: "hamburg", label: "Hamburg", flag: "🇩🇪", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "hanoi", label: "Hanoi", flag: "🇻🇳", tz: "Asia/Bangkok", utcOffset: "+07:00" },
  { id: "harare", label: "Harare", flag: "🇿🇼", tz: "Africa/Harare", utcOffset: "+02:00" },
  { id: "havana", label: "Havana", flag: "🇨🇺", tz: "America/Havana", utcOffset: "-05:00" },
  { id: "helsinki", label: "Helsinki", flag: "🇫🇮", tz: "Europe/Helsinki", utcOffset: "+02:00" },
  {
    id: "ho-chi-minh",
    label: "Ho Chi Minh",
    flag: "🇻🇳",
    tz: "Asia/Ho_Chi_Minh",
    utcOffset: "+07:00",
  },
  { id: "hong-kong", label: "Hong Kong", flag: "🇭🇰", tz: "Asia/Hong_Kong", utcOffset: "+08:00" },
  { id: "honolulu", label: "Honolulu", flag: "🇺🇸", tz: "Pacific/Honolulu", utcOffset: "-10:00" },
  { id: "houston", label: "Houston", flag: "🇺🇸", tz: "America/Chicago", utcOffset: "-06:00" },
  { id: "hyderabad", label: "Hyderabad", flag: "🇮🇳", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "islamabad", label: "Islamabad", flag: "🇵🇰", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "istanbul", label: "Istanbul", flag: "🇹🇷", tz: "Europe/Istanbul", utcOffset: "+03:00" },
  { id: "jakarta", label: "Jakarta", flag: "🇮🇩", tz: "Asia/Jakarta", utcOffset: "+07:00" },
  { id: "jeddah", label: "Jeddah", flag: "🇸🇦", tz: "Asia/Riyadh", utcOffset: "+03:00" },
  { id: "jerusalem", label: "Jerusalem", flag: "🇮🇱", tz: "Asia/Jerusalem", utcOffset: "+02:00" },
  {
    id: "johannesburg",
    label: "Johannesburg",
    flag: "🇿🇦",
    tz: "Africa/Johannesburg",
    utcOffset: "+02:00",
  },
  { id: "kabul", label: "Kabul", flag: "🇦🇫", tz: "Asia/Kabul", utcOffset: "+04:30" },
  { id: "kampala", label: "Kampala", flag: "🇺🇬", tz: "Africa/Kampala", utcOffset: "+03:00" },
  { id: "karachi", label: "Karachi", flag: "🇵🇰", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "kathmandu", label: "Kathmandu", flag: "🇳🇵", tz: "Asia/Kathmandu", utcOffset: "+05:45" },
  { id: "khartoum", label: "Khartoum", flag: "🇸🇩", tz: "Africa/Khartoum", utcOffset: "+02:00" },
  { id: "kigali", label: "Kigali", flag: "🇷🇼", tz: "Africa/Kigali", utcOffset: "+02:00" },
  { id: "kingston", label: "Kingston", flag: "🇯🇲", tz: "America/Jamaica", utcOffset: "-05:00" },
  {
    id: "kuala-lumpur",
    label: "Kuala Lumpur",
    flag: "🇲🇾",
    tz: "Asia/Kuala_Lumpur",
    utcOffset: "+08:00",
  },
  { id: "kuwait-city", label: "Kuwait City", flag: "🇰🇼", tz: "Asia/Kuwait", utcOffset: "+03:00" },
  { id: "kyiv", label: "Kyiv", flag: "🇺🇦", tz: "Europe/Kyiv", utcOffset: "+02:00" },
  { id: "lagos", label: "Lagos", flag: "🇳🇬", tz: "Africa/Lagos", utcOffset: "+01:00" },
  { id: "lahore", label: "Lahore", flag: "🇵🇰", tz: "Asia/Karachi", utcOffset: "+05:00" },
  { id: "la-paz", label: "La Paz", flag: "🇧🇴", tz: "America/La_Paz", utcOffset: "-04:00" },
  {
    id: "las-vegas",
    label: "Las Vegas",
    flag: "🇺🇸",
    tz: "America/Los_Angeles",
    utcOffset: "-08:00",
  },
  { id: "lima", label: "Lima", flag: "🇵🇪", tz: "America/Lima", utcOffset: "-05:00" },
  { id: "lisbon", label: "Lisbon", flag: "🇵🇹", tz: "Europe/Lisbon", utcOffset: "+00:00" },
  { id: "london", label: "London", flag: "🇬🇧", tz: "Europe/London", utcOffset: "+00:00" },
  {
    id: "los-angeles",
    label: "Los Angeles",
    flag: "🇺🇸",
    tz: "America/Los_Angeles",
    utcOffset: "-08:00",
  },
  { id: "luanda", label: "Luanda", flag: "🇦🇴", tz: "Africa/Luanda", utcOffset: "+01:00" },
  {
    id: "luxembourg",
    label: "Luxembourg",
    flag: "🇱🇺",
    tz: "Europe/Luxembourg",
    utcOffset: "+01:00",
  },
  { id: "madrid", label: "Madrid", flag: "🇪🇸", tz: "Europe/Madrid", utcOffset: "+01:00" },
  { id: "manama", label: "Manama", flag: "🇧🇭", tz: "Asia/Bahrain", utcOffset: "+03:00" },
  { id: "manila", label: "Manila", flag: "🇵🇭", tz: "Asia/Manila", utcOffset: "+08:00" },
  { id: "maputo", label: "Maputo", flag: "🇲🇿", tz: "Africa/Maputo", utcOffset: "+02:00" },
  { id: "medellin", label: "Medellin", flag: "🇨🇴", tz: "America/Bogota", utcOffset: "-05:00" },
  {
    id: "melbourne",
    label: "Melbourne",
    flag: "🇦🇺",
    tz: "Australia/Melbourne",
    utcOffset: "+11:00",
  },
  {
    id: "mexico-city",
    label: "Mexico City",
    flag: "🇲🇽",
    tz: "America/Mexico_City",
    utcOffset: "-06:00",
  },
  { id: "miami", label: "Miami", flag: "🇺🇸", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "milan", label: "Milan", flag: "🇮🇹", tz: "Europe/Rome", utcOffset: "+01:00" },
  {
    id: "minneapolis",
    label: "Minneapolis",
    flag: "🇺🇸",
    tz: "America/Chicago",
    utcOffset: "-06:00",
  },
  {
    id: "montevideo",
    label: "Montevideo",
    flag: "🇺🇾",
    tz: "America/Montevideo",
    utcOffset: "-03:00",
  },
  { id: "montreal", label: "Montreal", flag: "🇨🇦", tz: "America/Toronto", utcOffset: "-05:00" },
  { id: "moscow", label: "Moscow", flag: "🇷🇺", tz: "Europe/Moscow", utcOffset: "+03:00" },
  { id: "mumbai", label: "Mumbai", flag: "🇮🇳", tz: "Asia/Kolkata", utcOffset: "+05:30" },
  { id: "munich", label: "Munich", flag: "🇩🇪", tz: "Europe/Berlin", utcOffset: "+01:00" },
  { id: "muscat", label: "Muscat", flag: "🇴🇲", tz: "Asia/Muscat", utcOffset: "+04:00" },
  { id: "nairobi", label: "Nairobi", flag: "🇰🇪", tz: "Africa/Nairobi", utcOffset: "+03:00" },
  { id: "naples", label: "Naples", flag: "🇮🇹", tz: "Europe/Rome", utcOffset: "+01:00" },
  { id: "new-york", label: "New York", flag: "🇺🇸", tz: "America/New_York", utcOffset: "-05:00" },
  { id: "osaka", label: "Osaka", flag: "🇯🇵", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "oslo", label: "Oslo", flag: "🇳🇴", tz: "Europe/Oslo", utcOffset: "+01:00" },
  { id: "ottawa", label: "Ottawa", flag: "🇨🇦", tz: "America/Toronto", utcOffset: "-05:00" },
  {
    id: "panama-city",
    label: "Panama City",
    flag: "🇵🇦",
    tz: "America/Panama",
    utcOffset: "-05:00",
  },
  { id: "paris", label: "Paris", flag: "🇫🇷", tz: "Europe/Paris", utcOffset: "+01:00" },
  { id: "perth", label: "Perth", flag: "🇦🇺", tz: "Australia/Perth", utcOffset: "+08:00" },
  {
    id: "philadelphia",
    label: "Philadelphia",
    flag: "🇺🇸",
    tz: "America/New_York",
    utcOffset: "-05:00",
  },
  { id: "phnom-penh", label: "Phnom Penh", flag: "🇰🇭", tz: "Asia/Phnom_Penh", utcOffset: "+07:00" },
  { id: "phoenix", label: "Phoenix", flag: "🇺🇸", tz: "America/Phoenix", utcOffset: "-07:00" },
  {
    id: "port-moresby",
    label: "Port Moresby",
    flag: "🇵🇬",
    tz: "Pacific/Port_Moresby",
    utcOffset: "+10:00",
  },
  { id: "prague", label: "Prague", flag: "🇨🇿", tz: "Europe/Prague", utcOffset: "+01:00" },
  { id: "quito", label: "Quito", flag: "🇪🇨", tz: "America/Guayaquil", utcOffset: "-05:00" },
  { id: "rabat", label: "Rabat", flag: "🇲🇦", tz: "Africa/Casablanca", utcOffset: "+01:00" },
  {
    id: "rio-de-janeiro",
    label: "Rio de Janeiro",
    flag: "🇧🇷",
    tz: "America/Sao_Paulo",
    utcOffset: "-03:00",
  },
  { id: "riyadh", label: "Riyadh", flag: "🇸🇦", tz: "Asia/Riyadh", utcOffset: "+03:00" },
  { id: "rome", label: "Rome", flag: "🇮🇹", tz: "Europe/Rome", utcOffset: "+01:00" },
  {
    id: "san-diego",
    label: "San Diego",
    flag: "🇺🇸",
    tz: "America/Los_Angeles",
    utcOffset: "-08:00",
  },
  {
    id: "san-francisco",
    label: "San Francisco",
    flag: "🇺🇸",
    tz: "America/Los_Angeles",
    utcOffset: "-08:00",
  },
  { id: "san-jose", label: "San Jose", flag: "🇨🇷", tz: "America/Costa_Rica", utcOffset: "-06:00" },
  { id: "san-juan", label: "San Juan", flag: "🇵🇷", tz: "America/Puerto_Rico", utcOffset: "-04:00" },
  { id: "santiago", label: "Santiago", flag: "🇨🇱", tz: "America/Santiago", utcOffset: "-03:00" },
  { id: "sao-paulo", label: "Sao Paulo", flag: "🇧🇷", tz: "America/Sao_Paulo", utcOffset: "-03:00" },
  { id: "seattle", label: "Seattle", flag: "🇺🇸", tz: "America/Los_Angeles", utcOffset: "-08:00" },
  { id: "seoul", label: "Seoul", flag: "🇰🇷", tz: "Asia/Seoul", utcOffset: "+09:00" },
  { id: "shanghai", label: "Shanghai", flag: "🇨🇳", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "shenzhen", label: "Shenzhen", flag: "🇨🇳", tz: "Asia/Shanghai", utcOffset: "+08:00" },
  { id: "singapore", label: "Singapore", flag: "🇸🇬", tz: "Asia/Singapore", utcOffset: "+08:00" },
  { id: "sofia", label: "Sofia", flag: "🇧🇬", tz: "Europe/Sofia", utcOffset: "+02:00" },
  { id: "stockholm", label: "Stockholm", flag: "🇸🇪", tz: "Europe/Stockholm", utcOffset: "+01:00" },
  {
    id: "st-petersburg",
    label: "St Petersburg",
    flag: "🇷🇺",
    tz: "Europe/Moscow",
    utcOffset: "+03:00",
  },
  { id: "suva", label: "Suva", flag: "🇫🇯", tz: "Pacific/Fiji", utcOffset: "+12:00" },
  { id: "sydney", label: "Sydney", flag: "🇦🇺", tz: "Australia/Sydney", utcOffset: "+11:00" },
  { id: "tallinn", label: "Tallinn", flag: "🇪🇪", tz: "Europe/Tallinn", utcOffset: "+02:00" },
  { id: "tashkent", label: "Tashkent", flag: "🇺🇿", tz: "Asia/Tashkent", utcOffset: "+05:00" },
  { id: "tehran", label: "Tehran", flag: "🇮🇷", tz: "Asia/Tehran", utcOffset: "+03:30" },
  { id: "tel-aviv", label: "Tel Aviv", flag: "🇮🇱", tz: "Asia/Jerusalem", utcOffset: "+02:00" },
  { id: "tokyo", label: "Tokyo", flag: "🇯🇵", tz: "Asia/Tokyo", utcOffset: "+09:00" },
  { id: "toronto", label: "Toronto", flag: "🇨🇦", tz: "America/Toronto", utcOffset: "-05:00" },
  { id: "tripoli", label: "Tripoli", flag: "🇱🇾", tz: "Africa/Tripoli", utcOffset: "+02:00" },
  { id: "tunis", label: "Tunis", flag: "🇹🇳", tz: "Africa/Tunis", utcOffset: "+01:00" },
  {
    id: "ulaanbaatar",
    label: "Ulaanbaatar",
    flag: "🇲🇳",
    tz: "Asia/Ulaanbaatar",
    utcOffset: "+08:00",
  },
  { id: "vancouver", label: "Vancouver", flag: "🇨🇦", tz: "America/Vancouver", utcOffset: "-08:00" },
  { id: "vienna", label: "Vienna", flag: "🇦🇹", tz: "Europe/Vienna", utcOffset: "+01:00" },
  { id: "vientiane", label: "Vientiane", flag: "🇱🇦", tz: "Asia/Vientiane", utcOffset: "+07:00" },
  { id: "vilnius", label: "Vilnius", flag: "🇱🇹", tz: "Europe/Vilnius", utcOffset: "+02:00" },
  { id: "warsaw", label: "Warsaw", flag: "🇵🇱", tz: "Europe/Warsaw", utcOffset: "+01:00" },
  {
    id: "washington-dc",
    label: "Washington DC",
    flag: "🇺🇸",
    tz: "America/New_York",
    utcOffset: "-05:00",
  },
  {
    id: "wellington",
    label: "Wellington",
    flag: "🇳🇿",
    tz: "Pacific/Auckland",
    utcOffset: "+13:00",
  },
  { id: "windhoek", label: "Windhoek", flag: "🇳🇦", tz: "Africa/Windhoek", utcOffset: "+02:00" },
  { id: "yangon", label: "Yangon", flag: "🇲🇲", tz: "Asia/Yangon", utcOffset: "+06:30" },
  { id: "yaounde", label: "Yaounde", flag: "🇨🇲", tz: "Africa/Douala", utcOffset: "+01:00" },
  { id: "yerevan", label: "Yerevan", flag: "🇦🇲", tz: "Asia/Yerevan", utcOffset: "+04:00" },
  { id: "zagreb", label: "Zagreb", flag: "🇭🇷", tz: "Europe/Zagreb", utcOffset: "+01:00" },
  { id: "zurich", label: "Zurich", flag: "🇨🇭", tz: "Europe/Zurich", utcOffset: "+01:00" },
]

export const cityMapping = new Map(allCities.map((city) => [city.id, city]))

export const defaultCityIds = ["new-york", "london", "tokyo", "sydney", "paris"]

export const defaultCities = allCities.filter((city) => defaultCityIds.includes(city.id))

const now = new Date()
const getUtcOffset = (timeZone: string) => {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    timeZoneName: "shortOffset",
  }).formatToParts(now)
  const tzPart = parts.find((p) => p.type === "timeZoneName")?.value ?? "GMT"

  if (tzPart === "GMT" || tzPart === "UTC") return "+00:00"
  const match = tzPart.match(/GMT([+-]\d{1,2})(?::(\d{2}))?/)
  if (!match) return "+00:00"

  const sign = match[1].startsWith("-") ? "-" : "+"
  const hours = Math.abs(parseInt(match[1], 10))
  const minutes = match[2] ? parseInt(match[2], 10) : 0
  return `${sign}${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}`
}

const localTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone
export const localCity = {
  id: "local",
  label: "Local Time",
  tz: localTimezone,
  utcOffset: getUtcOffset(localTimezone),
}
