import type { City } from "../types/city"

export const cities: City[] = [
  { id: "abidjan", label: "Abidjan", tz: "Africa/Abidjan" },
  { id: "abu-dhabi", label: "Abu Dhabi", tz: "Asia/Dubai" },
  { id: "accra", label: "Accra", tz: "Africa/Accra" },
  { id: "addis-ababa", label: "Addis Ababa", tz: "Africa/Addis_Ababa" },
  { id: "adelaide", label: "Adelaide", tz: "Australia/Adelaide" },
  { id: "alexandria", label: "Alexandria", tz: "Africa/Cairo" },
  { id: "algiers", label: "Algiers", tz: "Africa/Algiers" },
  { id: "almaty", label: "Almaty", tz: "Asia/Almaty" },
  { id: "amman", label: "Amman", tz: "Asia/Amman" },
  { id: "amsterdam", label: "Amsterdam", tz: "Europe/Amsterdam" },
  { id: "anchorage", label: "Anchorage", tz: "America/Anchorage" },
  { id: "athens", label: "Athens", tz: "Europe/Athens" },
  { id: "atlanta", label: "Atlanta", tz: "America/New_York" },
  { id: "auckland", label: "Auckland", tz: "Pacific/Auckland" },
  { id: "baghdad", label: "Baghdad", tz: "Asia/Baghdad" },
  { id: "baku", label: "Baku", tz: "Asia/Baku" },
  { id: "bangkok", label: "Bangkok", tz: "Asia/Bangkok" },
  { id: "barcelona", label: "Barcelona", tz: "Europe/Madrid" },
  { id: "beijing", label: "Beijing", tz: "Asia/Shanghai" },
  { id: "beirut", label: "Beirut", tz: "Asia/Beirut" },
  { id: "belgrade", label: "Belgrade", tz: "Europe/Belgrade" },
  { id: "bengaluru", label: "Bengaluru", tz: "Asia/Kolkata" },
  { id: "berlin", label: "Berlin", tz: "Europe/Berlin" },
  { id: "bogota", label: "Bogota", tz: "America/Bogota" },
  { id: "boston", label: "Boston", tz: "America/New_York" },
  { id: "brasilia", label: "Brasilia", tz: "America/Sao_Paulo" },
  { id: "brisbane", label: "Brisbane", tz: "Australia/Brisbane" },
  { id: "brussels", label: "Brussels", tz: "Europe/Brussels" },
  { id: "bucharest", label: "Bucharest", tz: "Europe/Bucharest" },
  { id: "budapest", label: "Budapest", tz: "Europe/Budapest" },
  { id: "buenos-aires", label: "Buenos Aires", tz: "America/Argentina/Buenos_Aires" },
  { id: "busan", label: "Busan", tz: "Asia/Seoul" },
  { id: "cairo", label: "Cairo", tz: "Africa/Cairo" },
  { id: "calgary", label: "Calgary", tz: "America/Edmonton" },
  { id: "canberra", label: "Canberra", tz: "Australia/Sydney" },
  { id: "cape-town", label: "Cape Town", tz: "Africa/Johannesburg" },
  { id: "caracas", label: "Caracas", tz: "America/Caracas" },
  { id: "casablanca", label: "Casablanca", tz: "Africa/Casablanca" },
  { id: "chennai", label: "Chennai", tz: "Asia/Kolkata" },
  { id: "chicago", label: "Chicago", tz: "America/Chicago" },
  { id: "chittagong", label: "Chittagong", tz: "Asia/Dhaka" },
  { id: "christchurch", label: "Christchurch", tz: "Pacific/Auckland" },
  { id: "colombo", label: "Colombo", tz: "Asia/Colombo" },
  { id: "copenhagen", label: "Copenhagen", tz: "Europe/Copenhagen" },
  { id: "dakar", label: "Dakar", tz: "Africa/Dakar" },
  { id: "dallas", label: "Dallas", tz: "America/Chicago" },
  { id: "dar-es-salaam", label: "Dar es Salaam", tz: "Africa/Dar_es_Salaam" },
  { id: "delhi", label: "Delhi", tz: "Asia/Kolkata" },
  { id: "denver", label: "Denver", tz: "America/Denver" },
  { id: "dhaka", label: "Dhaka", tz: "Asia/Dhaka" },
  { id: "doha", label: "Doha", tz: "Asia/Qatar" },
  { id: "dubai", label: "Dubai", tz: "Asia/Dubai" },
  { id: "dublin", label: "Dublin", tz: "Europe/Dublin" },
  { id: "durban", label: "Durban", tz: "Africa/Johannesburg" },
  { id: "edinburgh", label: "Edinburgh", tz: "Europe/London" },
  { id: "edmonton", label: "Edmonton", tz: "America/Edmonton" },
  { id: "frankfurt", label: "Frankfurt", tz: "Europe/Berlin" },
  { id: "fukuoka", label: "Fukuoka", tz: "Asia/Tokyo" },
  { id: "geneva", label: "Geneva", tz: "Europe/Zurich" },
  { id: "guangzhou", label: "Guangzhou", tz: "Asia/Shanghai" },
  { id: "guatemala-city", label: "Guatemala City", tz: "America/Guatemala" },
  { id: "guayaquil", label: "Guayaquil", tz: "America/Guayaquil" },
  { id: "hamburg", label: "Hamburg", tz: "Europe/Berlin" },
  { id: "hanoi", label: "Hanoi", tz: "Asia/Bangkok" },
  { id: "harare", label: "Harare", tz: "Africa/Harare" },
  { id: "havana", label: "Havana", tz: "America/Havana" },
  { id: "helsinki", label: "Helsinki", tz: "Europe/Helsinki" },
  { id: "ho-chi-minh-city", label: "Ho Chi Minh City", tz: "Asia/Ho_Chi_Minh" },
  { id: "hong-kong", label: "Hong Kong", tz: "Asia/Hong_Kong" },
  { id: "honolulu", label: "Honolulu", tz: "Pacific/Honolulu" },
  { id: "houston", label: "Houston", tz: "America/Chicago" },
  { id: "hyderabad", label: "Hyderabad", tz: "Asia/Kolkata" },
  { id: "islamabad", label: "Islamabad", tz: "Asia/Karachi" },
  { id: "istanbul", label: "Istanbul", tz: "Europe/Istanbul" },
  { id: "jakarta", label: "Jakarta", tz: "Asia/Jakarta" },
  { id: "jeddah", label: "Jeddah", tz: "Asia/Riyadh" },
  { id: "jerusalem", label: "Jerusalem", tz: "Asia/Jerusalem" },
  { id: "johannesburg", label: "Johannesburg", tz: "Africa/Johannesburg" },
  { id: "kabul", label: "Kabul", tz: "Asia/Kabul" },
  { id: "kampala", label: "Kampala", tz: "Africa/Kampala" },
  { id: "karachi", label: "Karachi", tz: "Asia/Karachi" },
  { id: "kathmandu", label: "Kathmandu", tz: "Asia/Kathmandu" },
  { id: "khartoum", label: "Khartoum", tz: "Africa/Khartoum" },
  { id: "kigali", label: "Kigali", tz: "Africa/Kigali" },
  { id: "kingston", label: "Kingston", tz: "America/Jamaica" },
  { id: "kuala-lumpur", label: "Kuala Lumpur", tz: "Asia/Kuala_Lumpur" },
  { id: "kuwait-city", label: "Kuwait City", tz: "Asia/Kuwait" },
  { id: "kyiv", label: "Kyiv", tz: "Europe/Kyiv" },
  { id: "lagos", label: "Lagos", tz: "Africa/Lagos" },
  { id: "lahore", label: "Lahore", tz: "Asia/Karachi" },
  { id: "la-paz", label: "La Paz", tz: "America/La_Paz" },
  { id: "las-vegas", label: "Las Vegas", tz: "America/Los_Angeles" },
  { id: "lima", label: "Lima", tz: "America/Lima" },
  { id: "lisbon", label: "Lisbon", tz: "Europe/Lisbon" },
  { id: "london", label: "London", tz: "Europe/London" },
  { id: "los-angeles", label: "Los Angeles", tz: "America/Los_Angeles" },
  { id: "luanda", label: "Luanda", tz: "Africa/Luanda" },
  { id: "luxembourg", label: "Luxembourg", tz: "Europe/Luxembourg" },
  { id: "madrid", label: "Madrid", tz: "Europe/Madrid" },
  { id: "manama", label: "Manama", tz: "Asia/Bahrain" },
  { id: "manila", label: "Manila", tz: "Asia/Manila" },
  { id: "maputo", label: "Maputo", tz: "Africa/Maputo" },
  { id: "medellin", label: "Medellin", tz: "America/Bogota" },
  { id: "melbourne", label: "Melbourne", tz: "Australia/Melbourne" },
  { id: "mexico-city", label: "Mexico City", tz: "America/Mexico_City" },
  { id: "miami", label: "Miami", tz: "America/New_York" },
  { id: "milan", label: "Milan", tz: "Europe/Rome" },
  { id: "minneapolis", label: "Minneapolis", tz: "America/Chicago" },
  { id: "montevideo", label: "Montevideo", tz: "America/Montevideo" },
  { id: "montreal", label: "Montreal", tz: "America/Toronto" },
  { id: "moscow", label: "Moscow", tz: "Europe/Moscow" },
  { id: "mumbai", label: "Mumbai", tz: "Asia/Kolkata" },
  { id: "munich", label: "Munich", tz: "Europe/Berlin" },
  { id: "muscat", label: "Muscat", tz: "Asia/Muscat" },
  { id: "nairobi", label: "Nairobi", tz: "Africa/Nairobi" },
  { id: "naples", label: "Naples", tz: "Europe/Rome" },
  { id: "new-york", label: "New York", tz: "America/New_York" },
  { id: "osaka", label: "Osaka", tz: "Asia/Tokyo" },
  { id: "oslo", label: "Oslo", tz: "Europe/Oslo" },
  { id: "ottawa", label: "Ottawa", tz: "America/Toronto" },
  { id: "panama-city", label: "Panama City", tz: "America/Panama" },
  { id: "paris", label: "Paris", tz: "Europe/Paris" },
  { id: "perth", label: "Perth", tz: "Australia/Perth" },
  { id: "philadelphia", label: "Philadelphia", tz: "America/New_York" },
  { id: "phnom-penh", label: "Phnom Penh", tz: "Asia/Phnom_Penh" },
  { id: "phoenix", label: "Phoenix", tz: "America/Phoenix" },
  { id: "port-moresby", label: "Port Moresby", tz: "Pacific/Port_Moresby" },
  { id: "prague", label: "Prague", tz: "Europe/Prague" },
  { id: "quito", label: "Quito", tz: "America/Guayaquil" },
  { id: "rabat", label: "Rabat", tz: "Africa/Casablanca" },
  { id: "rio-de-janeiro", label: "Rio de Janeiro", tz: "America/Sao_Paulo" },
  { id: "riyadh", label: "Riyadh", tz: "Asia/Riyadh" },
  { id: "rome", label: "Rome", tz: "Europe/Rome" },
  { id: "san-diego", label: "San Diego", tz: "America/Los_Angeles" },
  { id: "san-francisco", label: "San Francisco", tz: "America/Los_Angeles" },
  { id: "san-jose", label: "San Jose", tz: "America/Costa_Rica" },
  { id: "san-juan", label: "San Juan", tz: "America/Puerto_Rico" },
  { id: "santiago", label: "Santiago", tz: "America/Santiago" },
  { id: "sao-paulo", label: "Sao Paulo", tz: "America/Sao_Paulo" },
  { id: "seattle", label: "Seattle", tz: "America/Los_Angeles" },
  { id: "seoul", label: "Seoul", tz: "Asia/Seoul" },
  { id: "shanghai", label: "Shanghai", tz: "Asia/Shanghai" },
  { id: "shenzhen", label: "Shenzhen", tz: "Asia/Shanghai" },
  { id: "singapore", label: "Singapore", tz: "Asia/Singapore" },
  { id: "sofia", label: "Sofia", tz: "Europe/Sofia" },
  { id: "stockholm", label: "Stockholm", tz: "Europe/Stockholm" },
  { id: "st-petersburg", label: "St Petersburg", tz: "Europe/Moscow" },
  { id: "suva", label: "Suva", tz: "Pacific/Fiji" },
  { id: "sydney", label: "Sydney", tz: "Australia/Sydney" },
  { id: "tallinn", label: "Tallinn", tz: "Europe/Tallinn" },
  { id: "tashkent", label: "Tashkent", tz: "Asia/Tashkent" },
  { id: "tehran", label: "Tehran", tz: "Asia/Tehran" },
  { id: "tel-aviv", label: "Tel Aviv", tz: "Asia/Jerusalem" },
  { id: "tokyo", label: "Tokyo", tz: "Asia/Tokyo" },
  { id: "toronto", label: "Toronto", tz: "America/Toronto" },
  { id: "tripoli", label: "Tripoli", tz: "Africa/Tripoli" },
  { id: "tunis", label: "Tunis", tz: "Africa/Tunis" },
  { id: "ulaanbaatar", label: "Ulaanbaatar", tz: "Asia/Ulaanbaatar" },
  { id: "vancouver", label: "Vancouver", tz: "America/Vancouver" },
  { id: "vienna", label: "Vienna", tz: "Europe/Vienna" },
  { id: "vientiane", label: "Vientiane", tz: "Asia/Vientiane" },
  { id: "vilnius", label: "Vilnius", tz: "Europe/Vilnius" },
  { id: "warsaw", label: "Warsaw", tz: "Europe/Warsaw" },
  { id: "washington-dc", label: "Washington DC", tz: "America/New_York" },
  { id: "wellington", label: "Wellington", tz: "Pacific/Auckland" },
  { id: "windhoek", label: "Windhoek", tz: "Africa/Windhoek" },
  { id: "yangon", label: "Yangon", tz: "Asia/Yangon" },
  { id: "yaounde", label: "Yaounde", tz: "Africa/Douala" },
  { id: "yerevan", label: "Yerevan", tz: "Asia/Yerevan" },
  { id: "zagreb", label: "Zagreb", tz: "Europe/Zagreb" },
  { id: "zurich", label: "Zurich", tz: "Europe/Zurich" },
]
